name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1
        run: echo "Hello World"
        
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Docker Image
        run: docker build -t thedevops91/web-application:latest .
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker Image to Docker Hub
        run:  docker push thedevops91/web-application:latest
