name: Build and Push Docker Image & Deploy To Minikube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1
        run: echo "Hello World"
        
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set Up Minikube
        uses: hashicorp/setup-minikube@v2
        
      - name: Start Minikube
        run:  minikube start
        
      - name: Build Docker Image
        run: docker build -t thedevops91/web-application:latest .
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push Docker Image to Docker Hub
        run:  docker push thedevops91/web-application:latest
        
      - name: Load Docker Image Into Minikube
        run:  minikube image load thedevops91/web-application:latest
        
      - name: Deploy Application on Minikube
        run:  |
          kubectl apply -f - deploy/deployment.yaml
          kubectl apply -f - deploy/service.yml
      
      - name: Expose Services
        run:  kubectl expose deployment web-application --type=NodePort --port=80
        
      - name: Print Minikube IP
        run: minikube ip
